version: '3.10'

services:
  db:
    image: postgres:14
    container_name: yimanbek_db
    restart: always
    environment:
      POSTGRES_USER: yimanbek_
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: barber_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    ports:
      - "6380:6379"

  web:
    build: .
    container_name: barber_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      -  db
      - redis
    command: /bin/bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  celery_worker:
    build: .
    container_name: barber_celery_worker
    restart: always
    working_dir: /usr/src/app
    command: celery -A services.tasks:app worker --loglevel=info
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    container_name: barber_celery_beat
    restart: always
    working_dir: /usr/src/app
    command: celery -A services.tasks:app beat --loglevel=info
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
      - celery_worker

volumes:
  pgdata: